### ISSUE TITLE
Publish the package to PyPi

### ISSUE THREAD

**Issue by eicca** [statice/anonymeter#10]
Right now anonymeter can be packaged and installed, however, it's not published to PyPi yet. I suggest to setup the following:

- [ ] add release process
- [ ] add automatic build on CI
- [ ] automatic publishing to PyPi on new releases
- [ ] (optional) publish and test from TestPyPi

@MatteoGiomi wdyt? Am I missing something?

**Comment by MatteoGiomi** [comment]
Hi @eicca, looks a good plan to me. I did not know about TestPyPi, it's cool!
