### ISSUE TITLE
Unable to view DEBUG messages

### ISSUE THREAD

**Issue by yoid2000** [statice/anonymeter#17]
There appears no way to view DEBUG log messages (or, at least, it is not documented).

Just FYI, note that I became interested in looking at the debug messages upon receiving the following failure message:

```
WARNING:root:Found 5000 failed queries out of 5000. Check DEBUG messages for more details.
```

Note also that I'm running anonymeter on a cluster with a shared file system. I run several hundred anonymeter jobs at once. If they all dump into the same file it might be a mess. I personally would prefer to option of allowing DEBUG messages to go to `stdout`. At a minimum, however, it should be possible to specify the log file (so that I can set it to the local file system rather than the shared file system).

**Comment by MatteoGiomi** [comment]
Thanks a lot @yoid2000 for opening this issue. Indeed the logging of Anonymeter can benefit from some more love.

**Comment by eicca** [comment]
Hi @yoid2000, thanks for submitting the issue.

We just merged the https://github.com/statice/anonymeter/pull/19. Please let us know if this solves the problem with the logging.
