### ISSUE TITLE
WARNING:root:Found 29 failed queries out of 500. Check DEBUG messages for more details

### ISSUE THREAD

**Issue by anushiya-rddi** [statice/anonymeter#20]
I am getting the above warning message when I evaluate my synthetic dataset for SinglingOut.

The dataset does not contain any null values. Upon checking the SinglingOutEvaluator class, it has a function to evaluate the random queries generated and this function throws the above warning. I am not sure why the random query generator is generating queries with null.

Can you explain this behavior better, please? and suggestions to overcome it?

**Comment by MatteoGiomi** [comment]
Hi @anushiya-rddi, thanks for reporting the issue. Just for my understanding: the evaluator generates queries which check for nan values, i.e., involving `pd.isna()`, although there are no nans in the data? This is should not happen, but even if it does, I wonder if that would be enough to have a failed query.. does the dataset have "weird" column names?

**Comment by eicca** [comment]
Closing it due to the lack of activity.
