### ISSUE TITLE
Update Dependency to Require pandas 2.0 or Higher

### ISSUE THREAD

**Issue by matheme-justyn** [statice/anonymeter#25]
Since the release of [`pandas` version 2.0.0 on April 3, 2023](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html), an increasing number of packages, particularly those related to differential privacy and/or synthetic data generation, have set their dependency on `pandas` to version 2.0 or higher. However, in the current [pyproject.toml](https://github.com/statice/anonymeter/blob/main/pyproject.toml) file of `anonymeter`, the `pandas` version restriction remains at 1.4 or higher within the 1.x series:

```python
    "pandas~=1.4",
```

I would suggest updating the compatibility declaration to raise the `pandas` dependency to 2.0 or above. Such an adjustment will facilitate easier integration of `anonymeter` with other data libraries.

Thank you for your attention, and I look forward to seeing this change implemented in future releases.

**Comment by eicca** [comment]
Hi @matheme-justyn, thanks for bringing this up! It definitely makes sense to support pandas >=2.0, we'd just have to make sure that anonymeter still works with pandas 2.0 first :)

However, I'd prefer not to drop support for >=1.4, as many people still use older versions of pandas, and that would be a huge inconvenience for existing users. So, after making sure that anonymeter still works with 2.0, I'd change the dependency to `>=1.4`. If everything goes smoothly, I can prepare a release soon.

**Comment by matheme-justyn** [comment]
I understand your consideration, and yes, we simply want to add support for `pandas 2.X`. While ensuring that it remains compatible with `pandas 1.X` using `pandas>=1.4` sounds reasonable.. Thanks for your works!

**Comment by eicca** [comment]
@matheme-justyn we just published the latest 1.0.0 release to pypi which relaxes the pandas requirements

**Comment by matheme-justyn** [comment]
I have been able to successfully use version 1.0.0 in my work. Thank you for your development efforts! :)
