### ISSUE TITLE
While using the Linkability and Inference Evaluators, what should be the value of the optional inputs "auxcols" and "secret" ? 

### ISSUE THREAD

**Issue by adityanandadec** [statice/anonymeter#28]

**Comment by MatteoGiomi** [comment]
Hi, 

Thanks for the question! The `aux_cols` (for inference and linkability) and `secret` columns (for inference) can be used to configure the evaluators to model a particular attack scenario. 
- `aux_cols` determines which attributes the attacker knows about its targets. For example, if your dataset contains demographic attributes  you could pass these to the `aux_cols` to model an attacker that obtains these attributes from social networks. 
- `secret` is only relevant to the `InferenceEvaluator` and specify what attribute of the targets the attacker will try to guess. 

Check the [example notebooks](https://github.com/statice/anonymeter/blob/main/notebooks/anonymeter_example.ipynb) for more details.
