### ISSUE TITLE
Inquiry on Processing Techniques and Access to Texas and US Census Datasets

### ISSUE THREAD

**Issue by Ryhhhh** [statice/anonymeter#31]
Hello，

Could you please provide more details on how you process Texas dataset and US Census dataset? Specifically, I am interested in any preprocessing steps, data cleaning methods, or specific attributes you focus on within these datasets.

Additionally, can you provide a file or link to the dataset you used?

**Comment by MatteoGiomi** [comment]
Hi @Ryhhhh, sorry for the late reply. Are you referring to the pre-processing of those datasets done for the experiments in the paper?

**Comment by MatteoGiomi** [comment]
I'm closing this. Feel free to re-open it.
