### ISSUE TITLE
InferenceEvaluator (Math Domain Error) P2

### ISSUE THREAD

**Issue by mdicio** [statice/anonymeter#32]
I know there is already an Issue about this however I see the conversation has not continued and I would like to expose how I am facing the same error to help understand this if I am doing something wrong, or to solve this if it is a bug. 
I was testing the library for the first time on a Synthetic Dataset created based on the housing dataset from sklearn. Everything worked fine. I then wanted to see what would happen if as a Synthetic Dataset I passed a copy of the original dataset, expecting to get some very high privacy risk values. Both the Singling Out and Linkability Evaluators worked correclty and gave me some near (im)perfect (1.0) privacy risks. However the Inference Evaluator gives an error.

ERROR:
```

File [c:\Users\c13811e\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\anonymeter\stats\confidence.py:104](file:///C:/Users/c13811e/.pyenv/pyenv-win/versions/3.11.0/Lib/site-packages/anonymeter/stats/confidence.py:104), in success_rate(n_total, n_success, confidence_level)
    [102](file:///C:/Users/c13811e/.pyenv/pyenv-win/versions/3.11.0/Lib/site-packages/anonymeter/stats/confidence.py:102) rate = (n_success + 0.5 * z_squared) / denominator
    [103](file:///C:/Users/c13811e/.pyenv/pyenv-win/versions/3.11.0/Lib/site-packages/anonymeter/stats/confidence.py:103) print(n_success_var)
--> [104](file:///C:/Users/c13811e/.pyenv/pyenv-win/versions/3.11.0/Lib/site-packages/anonymeter/stats/confidence.py:104) error = (z / denominator) * sqrt(n_success_var + 0.25 * z_squared)
    [105](file:///C:/Users/c13811e/.pyenv/pyenv-win/versions/3.11.0/Lib/site-packages/anonymeter/stats/confidence.py:105) return SuccessRate(value=rate, error=error)

ValueError: math domain error
```

Extra INFO:
Adding some prints in anonymeter/stats/confidence.py success_rate() function:

n_success = 18000
n_total = 3000
n_success_var = -90000.0
Why is n_success 6 times the n_total?

To reproduce the error you can run this code:

```
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing

datas = fetch_california_housing()

# Create a DataFrame from the data and target
df = pd.DataFrame(data=datas.data, columns=datas.feature_names)
df["target"] = datas.target
df.columns = [i.replace(" ", "_").strip() for i in df.columns]
df_train, df_test = train_test_split(df, test_size=0.2)

synth_df = df_train.copy()
evaluator = InferenceEvaluator(ori = df_train,
                       syn = synth_df,
                       control = df_test,
                       n_attacks = 3000,
                       aux_cols = list(df.columns)[:3],
                       secret = list(df.columns)[3:])

evaluator.evaluate()
risk = evaluator.risk()
print(risk)

```

**Comment by mdicio** [comment]
I figured out the issue, sorry. The error was caused by passing a secret with a list of multiple columns instead of 1 column. Maybe there could be a ValueError raised if one tries to pass multiple columns as secret. The secret is supposed to be only one column correct?

**Comment by eicca** [comment]
> I figured out the issue, sorry. The error was caused by passing a secret with a list of multiple columns instead of 1 column. Maybe there could be a ValueError raised if one tries to pass multiple columns as secret. The secret is supposed to be only one column correct?

Hi @mdiciol, thanks a lot for raising the issue and also figuring out the reason behind it :) Yes, the secret can be only one column: https://github.com/statice/anonymeter/blob/main/src/anonymeter/evaluators/inference_evaluator.py#L134

Your suggestion of raising a `ValueError` totally makes sense. I can take a look at it unless you'd like to make a contribution yourself :)

**Comment by mdicio** [comment]
Hi @eicca it would be nice if I could make the contribution if you don't mind.
