### ISSUE TITLE
Minor typos in singling_out_evaluator.py (and other files)

### ISSUE THREAD

**Issue by yoid2000** [statice/anonymeter#5]
evluation --> evaluation      (also in `anonymeter_example.ipynb`)

-----------
  
```
if not self._evaluated:
            raise RuntimeError("The inference evaluator wasn't evaluated yet. "
                               "Please, run `evaluate()` first.")
```

Should be "The singling_out evaluator".  Same typo is in `linkability_evaluator.py`

-------------

**Comment by eicca** [comment]
Thanks a lot @yoid2000 !
